name: samestr
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - biopython
  - bzip2
  - numpy
  - pandas
  - python=3.9
  - readline
  - blast >=2.6.0
  - muscle=3.8.1551
  - mafft=7.515
  - samtools=0.1.19
