name: samestr
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _r-mutex
  - binutils_impl_linux-64
  - binutils_linux-64
  - biopython
  - bwidget
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - curl
  - fontconfig
  - freetype
  - fribidi
  - gcc_impl_linux-64
  - gcc_linux-64
  - gettext
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - glib
  - graphite2
  - gsl
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - icu
  - jpeg
  - kernel-headers_linux-64
  - krb5
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libcurl
  - libedit
  - libffi
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran-ng
  - libgomp
  - libiconv
  - liblapack
  - libopenblas
  - libpng
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - make
  - ncurses
  - numpy
  - openssl
  - pandas
  - pandoc
  - pango
  - pcre
  - pip
  - pixman
  - pthread-stubs
  - python=3.9
  - pytz
  - readline
  - scipy
  - sed
  - setuptools
  - six
  - sqlite
  - sysroot_linux-64
  - tk
  - tktable
  - wheel
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd
  - blast >=2.6.0
  - muscle=3.8.1551
  - mafft=7.515
  - samtools=0.1.19
