#!/usr/bin/env python3
"""SameStr: Shared Strains Identification in Metagenomic Samples."""

import glob
import logging
import os
import pathlib

from datetime import datetime
from os.path import dirname, realpath, isfile
from os import environ
from sys import stderr, argv

import numpy as np

from samestr import __version__

from samestr.convert.convert_main import convert_main
from samestr.compare import compare
from samestr.db.db import db_main, load_db
from samestr.extract import ref2freq
from samestr.filter import filter_freqs
from samestr.merge.merge_main import merge_main
from samestr.stats import aln2stats
from samestr.summarize import summarize
from samestr.utils.clade_input import manage_clade_input
from samestr.utils.citations import citations
from samestr.utils.file_mapping import get_uniform_extension
from samestr.utils.ooSubprocess import parallelize_async, serialize
from samestr.utils.parse_args import read_params
from samestr.utils.utilities import read_json, write_json


## Check input file extensions
ACCEPTED_EXTENSIONS = {
    'db': ['.fasta', '.fa', '.fna', '.fasta.bz2', '.fa.bz2', '.fna.bz2'],
    'convert': ['.sam', '.sam.bz2', '.bam'],
    'extract': ['.fasta', '.fa', '.fna', '.fasta.gz', '.fa.gz', '.fna.gz'],
    'merge': ['.npy', '.npy.gz', '.npz'],
    'filter': ['.npy', '.npy.gz', '.npz'],
    'stats': ['.npy', '.npy.gz', '.npz'],
    'compare': ['.npy', '.npy.gz', '.npz'],
    'summarize': ['']
}

SAMESTR_DIR = dirname(realpath(__file__))
CONVERT_DIR = os.path.join(SAMESTR_DIR, 'convert', '')
UTILS_DIR = os.path.join(SAMESTR_DIR, 'utils', '')
environ['PATH'] += ':' + UTILS_DIR + ':' + CONVERT_DIR


def samestr(input_args):
    """Main function for SAMESTR."""
    
    ## Log command     
    samestr_cmd = {
        'version': f'{__version__}',
        'command': ' '.join(argv),
        'date-start': '%s' % datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    ## Get database manifest files
    if input_args['command'] == 'db':
        db_main(input_args, samestr_cmd, ACCEPTED_EXTENSIONS['db'])
        exit(0)
    
    input_args['samestr_db'] = load_db(input_args, samestr_cmd)

    pathlib.Path(input_args['output_dir']).mkdir(exist_ok=True, parents=True)

    input_clade = input_args.get("species")

    if input_args['command'] == 'summarize':
        cmd_args = serialize(summarize, [input_args])
    else:
        accepted_extensions = ACCEPTED_EXTENSIONS[input_args['command']]

        if input_args['command'] == 'merge':
            if not input_args['input_dir'] and not input_args['input_files']:
                raise ValueError("Neither --input-files not --input-dir are set.")
            elif input_args['input_files'] and input_args['input_dir']:
                raise ValueError("--input-files and --input-dir cannot be used simultaneously.")            
            elif args['input_dir']:
                args['input_files'] = glob.glob(os.path.join(args['input_dir'], "*", "*.npz"), recursive=True,)
                if not args['input_files']:
                    raise ValueError(f"Cannot find any .npz files in {args['input_dir']}.")

        input_args['input_extension'] = get_uniform_extension(
            input_args['input_files'], accepted_extensions)

        # Count input files
        file_count = len(input_args['input_files'])
        LOG.debug('Number of input files: %s', file_count)

        if input_args['command'] == 'extract':
            cmd_args = serialize(ref2freq, [input_args])
        elif input_args['command'] == 'convert':
            convert_main(input_args)
        elif input_args['command'] == 'merge':
            merge_main(input_args, input_clade)
        else:
            cmd_args, freqs = manage_clade_input(input_args, input_clade)

            if input_args['command'] == 'filter':
                LOG.info('Filtering files: %s', len(freqs))
                cmd_args = parallelize_async(filter_freqs, cmd_args, input_args['nprocs'])

            elif input_args['command'] == 'stats':
                LOG.info('Gathering statistics: %s', len(freqs))
                cmd_args = parallelize_async(aln2stats, cmd_args, input_args['nprocs'])

            elif input_args['command'] == 'compare':
                LOG.info('Comparing alignments: %s', len(freqs))
                cmd_args = parallelize_async(compare, cmd_args, input_args['nprocs'])
    
    # write current command to logfile
    samestr_cmd['date-end'] = '%s' % datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    logfile_fn = os.path.join(input_args['output_dir'], 'command_log.json')
    if isfile(logfile_fn):
        logfile = read_json(logfile_fn)
        iter = max([int(k) for k in logfile.keys()]) + 1
    else:
        logfile = {}
        iter = 1
    logfile[iter] = samestr_cmd
    write_json(logfile_fn, logfile)
    LOG.info('Done.')


if __name__ == "__main__":
    args = read_params()

    if args['citation'] is not None:
        print(citations[args['citation']])
        exit(0)

    if args.get('random_seed') is not None:
        np.random.seed(args['random_seed'])

    logging.basicConfig(
    level=getattr(logging, args['verbosity']),
    stream=stderr,
    format='%(asctime)s | %(levelname)s | %(name)s | %(funcName)s | %(lineno)d | %(message)s'
    )
    LOG = logging.getLogger(__name__)

    samestr(args)
